name: cd

on:
  push:
    branches: [main]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.0"
      - name: Build Project
        run: scripts/buildprod.sh
  setup-gcloud:
    name: setup-gcloud
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
        with:
          version: ">= 363.0.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, setup-gcloud]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Upload
        run: cd ../../ && gcloud builds submit --project=cicd-490919 --tag us-central1-docker.pkg.dev/cicd-490919/notely-ar-repo/strjkc/notely:latest .
